### ISSUE TITLE
As a curator I want to explore the use of OTU name in the data

### ISSUE THREAD

**Issue by mjy** [sfg-taxonpages/plecoptera#10]
See https://sfg.taxonworks.org/tasks/otus/filter?per=50&with_name=true&extend%5B%5D=taxonomy&page=1.

There are 438 OTUs with OTU `name` populated. These could be systematically checked and the name removed, or formalized to a TaxonName, or otherwise.  Starting with OTUs that have missmatched names might be the first thing to do.

**Comment by hhopkins77** [comment]
These have been gone through and all items possible have been cleared.
