### ISSUE TITLE
Incorrect distributions for Plecoptera: Brachypterainae Zwick, 1973

### ISSUE THREAD

**Issue by redewalt** [sfg-taxonpages/plecoptera#12]
Heidi,

I was checking on the spelling of a subfamily of Plecoptera. In doing so, I found some geographic distributions that don't make sense for Brachypterainae Zwick, 1973 in Plecoptera SF (see below). This subfamily should not be in S Am, central Africa, nor Madagascar. It could be in Northwest Africa in the Atlas Mountains, but nowhere else in the continent.

Of course, I will have to go through the entire hierarchy to root out problems in the data set. Please check on these errors and let me know how they could have been produced.

**Comment by mjy** [comment]
@redewalt French Guiana (South America) is a well know problem that has been reported repeatedly.  We are still discussing how to fix, it will persist for some time.

Madagascar is a new one.  It is possible for you to do a lot of debugging fairly efficiently with the filtering we have.  It might be worth reviewing this process with Lily and our help.

**Comment by hhopkins77** [comment]
I will bring this issue to the meeting on Wednesday, @mjy, and learn about the debugging you mention. 

@redewalt the issue with French Guiana is a known problem, but I don't know what might be going on with Central African Republic and Madagascar. I will take this to this week's meeting.

**Comment by lvhart2** [comment]
I will also sit in on this week's meeting to see this filtering in action.

**Comment by mjy** [comment]
In brief:

* Filter OTUs -> Select the taxon name in question, choose "descendants"
* Click filter
* At this point you can use the Funnel to move from OTU to 
  * Collecting Events
    * When present click the Eye (top right), then "Show map" 
  * Asserted Distributions
    * Scroll through the list for obvious targets
* You can also click on the "Linker" (on the left) and send all OTUs to the 'Cached map items" report
  * Here you can search through the list to find, for example "Madacascar"
  * Click on the OTU and it will return you to the OTU filter with that target
    * Repeat the AD/CE searches

For example, searching for clues for "Madagascar":

* Search for "Brachypterainae" with descendants: https://sfg.taxonworks.org/tasks/otus/filter?per=50&descendants=true&taxon_name_id%5B%5D=1001193&extend%5B%5D=taxonomy&page=1
* Send that via the "Linker" to the Cached map items report: https://sfg.taxonworks.org/tasks/cached_maps/report/items_by_otu?per=50&descendants=true&taxon_name_id%5B%5D=1001193
* Search in ^ for "Madagascar"
<img width="1134" alt="Screenshot 2023-10-02 at 12 49 54 PM" src="https://github.com/sfg-taxonpages/plecoptera/assets/22600/f74fce50-56d9-403a-9e1e-e025f6a9fad2">
* Click on the OTU, and repeat isolate specimens/asserted distributions

**Comment by mjy** [comment]
Madagascar intersect is due to Norway. https://sfg.taxonworks.org/geographic_areas/33835.  So there is more to this problemantic shape than (I believe it was one of the TDWG shapes we used) we anticipated.

This one could be handled by switching all Plecoptera Norway from TDWG to the Natural Earth version I believe.  We of course also will want to fix the shape/intersection problem at some point too.

**Comment by redewalt** [comment]
Have you had a change to find a home for the Perla pdf?

R. Edward DeWalt
University of Illinois
Illinois Natural History Survey
1816 S Oak St.
Champaign, Illinois 61820
***@***.***
217-649-7414
________________________________

**Comment by mjy** [comment]
We almost have it, found another set of issues that we have been resolving.

**Comment by redewalt** [comment]
Matt, it looks good. Thanks

**Comment by hhopkins77** [comment]
@mjy : Glad the Madagascar problem has been detected. Any ideas on Central African Republic?

**Comment by mjy** [comment]
@hhopkins77 It's probably the same class of problems I will demonstrate how you can confirm this (essentially the steps above) tomorrow, but in essence you need to find each asserted distribution geographic area and step through them in `/geographic_areas`, checking the preview map on the bottom right for which one shows the bad CAR data.

**Comment by hhopkins77** [comment]
Ok. More tomorrow when I will take some detailed notes.

**Comment by hhopkins77** [comment]
@mjy : I went through the steps from yesterday until I reached the cached map items report. I searched through cached map items report for CAR but did not find it. Without finding it at that step I can't proceed through the rest of the steps I wrote down yesterday. Need your instruction on how to proceed.

Also, under the Plecoptera species Brachyptera risi (the one with the Madagascar problem) there is also a cached map item for Toliary which is a district within Madagascar. This is also tied to the Norway tdwg_l3 map tile so I don't think it requires a separate issue to be filed, but wanted to check with you.

**Comment by lvhart2** [comment]
**Newfoundland is the culprit for CAR!** Maybe it is helpful to explain how I found it:
Filter OTUs->Search Brachypterainae in Taxon Name with descendants->Radial Filter on top left->Asserted Distributions-> this gave a 435 record result so I chose show 1000 records per page, then clicked Geographic Area field title to alphabetize the results.->In new tab in PSF TW project, go to Data-> open Geographic Areas->go down the list of filtered asserted distributions and search each unique geographic area for inconsistencies. 

@hhopkins77 I too went to the cached map report and it was really no help just looking at that alone, so I had to cross reference what it shows on the AD map "cached map report" with what it SHOULD list on filtered asserted distributions. 

@mjy The part I'm stuck on now is how you select the Natural Earth map tile instead. I remember we saw that Move button yesterday and I can't remember how we got there. Also where should I add this as an issue in GitHub? Thanks!

<img width="1440" alt="Screenshot 2023-10-05 at 12 17 14 PM" src="https://github.com/sfg-taxonpages/plecoptera/assets/75492546/e41f4abc-623f-44f7-b5c3-cab5c5076f3c">

**Comment by mjy** [comment]
Nice work @lvhart2.  We'll see if we can get the shapes fixed.

**Comment by mjy** [comment]
@lvhart2 Filter -> Asserted distributions -> after the result you can use the update icon:

<img width="1063" alt="Screenshot 2023-10-05 at 1 39 14 PM" src="https://github.com/sfg-taxonpages/plecoptera/assets/22600/4d3cde95-e5ff-442b-bba0-af084bac5198">

**Comment by hhopkins77** [comment]
@lvhart2 : excellent job! thanks for sharing how you found it. I moved the asserted distribution to the correct tile set for the one species with Newfoundland as an AD. I will file issue.
