### ISSUE TITLE
Arcynopteryx dichroa common name

### ISSUE THREAD

**Issue by redewalt** [sfg-taxonpages/plecoptera#13]
The common name "Holarctic Springfly" did not transfer for this species. Is there a wider issue?

**Comment by redewalt** [comment]
I have noticed several common names missing from Plecoptera SF. It is present for some and absent for others. It seems we will have to import them again. How is this best accomplished.

**Comment by klausriede** [comment]
this is standard SQL , using the respective tables (old vs new), connected via an ID or eventually name, using the UPDATE function.

**Comment by mjy** [comment]
@klausriede we do not use SQL directly, it's too easy to break the validation and semantics by doing that.  TaxonWorks has an ORM that we work through if we have to batch operate on the data.

@redewalt I do not have a full answer, but please see filters, I believe we can check for things with/out common names, if not we will add that shortly.

**Comment by hhopkins77** [comment]
@mjy I have never worked with common names before. Can you tell me where in TW I enter common names?

**Comment by mjy** [comment]
OTU -> Quick form.

**Comment by hhopkins77** [comment]
Ah ha. Got it.

**Comment by hhopkins77** [comment]
@mjy Update: I have checked this and two other Plecoptera species for missing common names. All have 2 or more OTUs, only one of which has the common name. This would seem to indicate that the multiple OTU issue is a big one, and that TaxonPages is not drawing data from the best (ie: the correct) OTU (not sure about that wording).

**Comment by klausriede** [comment]
What is an ORM? In any case you could/should validate migration results via the simple SQL routine I suggested. It is too tedious for us users to find the many mistakes, and it also does not look good for the outside world....

**Comment by hhopkins77** [comment]
I have cleared the migration issue that I believe was preventing some common names from showing. Should you find any more missing common names, please report the species name and the associated common name and it will be checked.
