### ISSUE TITLE
Reference error for Perlesta sublobata

### ISSUE THREAD

**Issue by nsears1000** [sfg-taxonpages/plecoptera#15]
The reference you supply in this account is:

South, E.J., DeWalt, R.E., Davis, M.A. & Thomas, M.J. (2019) A new stonefly species (Plecoptera: Perlidae) from southern USA, with morphological and molecular comparison to other taxa. Zookeys, 858, 45–70.

I believe the correct title is: 

A new stonefly species (Plecoptera, Perlidae) from the Interior Highlands USA, with morphological and molecular comparison to other congeneric species.

Thanks,
Nicole

**Comment by hhopkins77** [comment]
Thanks Nicole. Correction made.
