### ISSUE TITLE
PSF Homepage: _Acroneuria perplexa_ clickable link routes to _Anacroneuria perplexa_

### ISSUE THREAD

**Issue by lvhart2** [sfg-taxonpages/plecoptera#6]
When I click on the suggested species _Acroneuria perplexa_ link under the image, it routes to _Anacroneuria perplexa_, a species within a different genus. Please update link. Thanks!

<img width="1019" alt="Screenshot 2023-09-21 at 2 48 45 PM" src="https://github.com/sfg-taxonpages/plecoptera/assets/75492546/64c1886b-ce05-4064-85be-1516ed286b7d">
<img width="1340" alt="Screenshot 2023-09-21 at 2 49 58 PM" src="https://github.com/sfg-taxonpages/plecoptera/assets/75492546/469b4632-1974-4396-99ac-cd00d50b4b4c">

**Comment by debpaul** [comment]
Closing now. It's fixed.
